import { useEffect, useRef, useState } from 'react';
import { Microphone, Phone, ArrowRight, FolderOpen } from '@phosphor-icons/react';
import { nativeAvailable, nativeRequest, type NativeSnapshot } from '../lib/native';
import { PageIntro } from './shared';
interface Device { id: number; name: string; isVirtual: boolean }
interface Process { id: number; name: string; outputDeviceIDs: number[] }
interface CallSnapshot extends NativeSnapshot {
  state: string; error: string; nearDraft: string; farDraft: string; farLevel: number;
  microphonePermission: boolean; speechPermission: boolean; deviceError?: string;
  devices?: { inputs: Device[]; virtualOutputs: Device[]; processes: Process[] };
  lines: { id: string; side: string; original: string; translated: string; status: string }[];
}
export function Calls() {
  const native = nativeAvailable(); const [snapshot, setSnapshot] = useState<CallSnapshot>();
  const [input, setInput] = useState(''); const [output, setOutput] = useState(''); const [process, setProcess] = useState('');
  const [consent, setConsent] = useState(false); const [routing, setRouting] = useState(false);
  const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const pending = useRef(false);
  const [testText, setTestText] = useState('Hello. Could you speak a little more slowly?'); const [translated, setTranslated] = useState('');
  const translationGeneration = useRef(0);
  const refresh = async () => { if (pending.current) return; pending.current = true; try { setSnapshot(await nativeRequest<CallSnapshot>('snapshot')); } catch (e) { setError(e instanceof Error ? e.message : 'Could not read the companion.'); } finally { pending.current = false; } };
  useEffect(() => { if (!native) return; void refresh(); const timer = setInterval(() => void refresh(), 1200); return () => { clearInterval(timer); translationGeneration.current++; }; }, [native]);
  const act = async (command: Parameters<typeof nativeRequest>[0], payload?: Record<string, unknown>) => {
    if (busy) return; setBusy(true); setError('');
    try { const result = await nativeRequest(command, payload); await refresh(); return result; }
    catch (e) { setError(e instanceof Error ? e.message : 'The action could not finish.'); }
    finally { setBusy(false); }
  };
  const active = snapshot?.callActive;
  const audioPaused = snapshot?.state === 'audio paused';
  const physicalInputs = snapshot?.devices?.inputs.filter(d => !d.isVirtual) || [];
  return <><PageIntro label="SPANISH, IN THE MOMENT" title="Bring both sides together.">Live call translation in your Habla Mac companion. Speak English, send Spanish, and read what comes back.</PageIntro>
    {!native ? <section className="panel companion-guide"><span className="tag">MAC COMPANION</span><h2>Your call, with a little help.</h2><p>Live call audio needs the Habla Mac app. The website cannot access another app’s audio or send a virtual microphone into a call.</p><div className="button-row"><a className="button" href="habla://calls">Open Habla for Mac <ArrowRight size={18} /></a><a className="button secondary" href="#coach">Explore AI conversations</a></div><ol className="setup-steps"><li><strong>Open the installed companion.</strong><span>Requires Apple silicon, macOS 26 or later, and English and Spanish language packs.</span></li><li><strong>Choose your audio paths.</strong><span>Your physical microphone supplies English. BlackHole carries translated Spanish into your calling app. That app plays the other person through physical speakers or headphones.</span></li><li><strong>Start together.</strong><span>Tell everyone that translation and a local transcript are enabled. Choose the calling app in Habla, then start.</span></li></ol><p className="micro">The companion is built locally for this Mac. A signed public installer is not available yet. Web lessons and mission practice remain available to everyone.</p></section> : <>
    <section className="panel"><div className="section-line"><h2>{audioPaused ? 'Call audio paused' : active ? 'Translation is running' : 'Get ready for your call'}</h2><span className="tag">{snapshot?.state || 'Checking readiness'}</span></div>
      <p>English speech goes to Spanish audio. Spanish speech returns as English captions. The app leaves your system audio settings under your control.</p>
      <div className="button-row"><button className="button secondary small" disabled={busy || active} onClick={() => void act('permissions')}>Allow microphone & speech</button><button className="text-button" disabled={busy || active} onClick={() => void act('prepareTranslation')}>Prepare languages</button><button className="text-button" onClick={() => void refresh()}>Refresh readiness</button></div>
      <p className="micro">Microphone: {snapshot?.microphonePermission ? 'allowed' : 'permission needed'} · Speech: {snapshot?.speechPermission ? 'allowed' : 'permission needed'} · Translation: {snapshot?.translation.available ? 'ready offline' : snapshot?.translation.reason || 'checking'}</p>
      {!active && <><div className="form-columns call-routing"><label>1. Your physical microphone<select value={input} onChange={e => setInput(e.target.value)}><option value="">Choose a microphone</option>{physicalInputs.map(d => <option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label>2. Spanish audio output<select value={output} onChange={e => setOutput(e.target.value)}><option value="">Choose BlackHole</option>{snapshot?.devices?.virtualOutputs.map(d => <option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label>3. Calling app audio source<select value={process} onChange={e => setProcess(e.target.value)}><option value="">Choose an active call app</option>{snapshot?.devices?.processes.map(d => <option value={d.id} key={d.id}>{d.name} ({d.id})</option>)}</select></label></div>
      <p className="micro">Start your calling app first, then refresh. If captions stay quiet, select the process actually producing the call audio.</p>
      <label className="checkbox-label"><input type="checkbox" checked={routing} onChange={e => setRouting(e.target.checked)} />I set the calling app microphone to BlackHole and its speaker to physical speakers or headphones.</label><label className="checkbox-label"><input type="checkbox" checked={consent} onChange={e => setConsent(e.target.checked)} />Everyone knows translation and a transcript saved on this Mac are enabled.</label>
      <button className="button" disabled={busy || !input || !output || !process || !routing || !consent || !snapshot?.translation.available} onClick={() => void act('startCall', { inputID: Number(input), injectionID: Number(output), processID: Number(process), consent, physicalOutputConfirmed: routing })}><Phone size={19} />Start call translator</button></>}
      {active && <div className="call-controls"><div className="button-row"><button className="button" disabled={busy || audioPaused} onClick={() => void act(snapshot?.state === 'capturingHisUtterance' ? 'pttUp' : 'pttDown')}><Microphone size={20} />{snapshot?.state === 'capturingHisUtterance' ? 'Finish my turn' : 'Speak my English turn'}</button><button className="button secondary" disabled={busy} onClick={() => void act('endCall')}>End call & save</button></div><p className="micro">{audioPaused ? 'End and save this call, then restart the translator to restore audio.' : 'You can also hold Option + Space while Habla is focused. A new turn interrupts translated speech. Global hotkeys depend on macOS access.'}</p><div className="audio-level" role="meter" aria-label="Calling app audio level" aria-valuemin={0} aria-valuemax={1} aria-valuenow={Math.min(1, snapshot?.farLevel || 0)}><span style={{ width: `${Math.min(100, (snapshot?.farLevel || 0) * 500)}%` }} /></div><p className="micro">Incoming audio level. No movement means Habla is not receiving the selected app’s audio.</p></div>}
      {snapshot?.state === 'save failed' && <button className="button" disabled={busy} onClick={() => void act('endCall')}>Retry saving transcript</button>}
      {(error || snapshot?.error || snapshot?.deviceError) && <div className="error-banner" role="alert">{error || snapshot?.error || snapshot?.deviceError}</div>}
    </section>
    {(active || !!snapshot?.lines.length) && <section className="panel call-transcript"><div className="section-line"><h2>Both sides, in view.</h2><button className="text-button" onClick={() => void act('openTranscriptFolder')}><FolderOpen size={18} /> Saved transcripts</button></div><p className="micro">Only finalized speech is translated. Unfinished or failed translations are saved with their original text and no invented translation.</p><div aria-live="polite">{snapshot?.lines.map(line => <article className={`conversation-line ${line.side}`} key={line.id}><strong>{line.side === 'you' ? 'You · English → Spanish' : 'Them · Spanish → English'}</strong><p>{line.original}</p><p className="translation">{line.translated || (line.status === 'translating' && active ? 'Translating…' : 'Translation unavailable')}</p></article>)}</div>{snapshot?.nearDraft && <p className="notice">Your live draft: {snapshot.nearDraft}</p>}{snapshot?.farDraft && <p className="notice">Their live draft: {snapshot.farDraft}</p>}</section>}
    {!active && <section className="panel"><h2>Try a translation first.</h2><form onSubmit={e => { e.preventDefault(); const generation = ++translationGeneration.current; setTranslated(''); void act('translateText', { text: testText, direction: 'en-es' }).then(result => { if (generation === translationGeneration.current && typeof result?.text === 'string') setTranslated(result.text); }); }}><label htmlFor="translation-test">English phrase</label><textarea id="translation-test" value={testText} onChange={e => { translationGeneration.current++; setTestText(e.target.value); setTranslated(''); }} maxLength={1500} /><button className="button secondary" disabled={busy || !testText.trim()}>Translate to Spanish</button>{translated && <p className="story-text" lang="es" role="status">{translated}</p>}</form></section>}
    </>}
  </>;
}
