import { ArrowRight, BookOpen, Headphones, ChatCircleDots, Clock, CalendarBlank, Check, Plant, ArrowUpRight, Timer } from '@phosphor-icons/react';
import type { AppState, Mode, Unit } from '../types';
import { duePhrases, stats, activityAttempts, fluentPhrases } from '../lib/engine';
import { Meter } from './shared';
type Props = { state: AppState; units: Unit[]; start: (mode: Mode, id?: string) => void; startDialogue: (unitId: string) => void };
export function Dashboard({ state, units, start, startDialogue }: Props) {
  const activity = activityAttempts(state); const data = stats(state); const due = duePhrases(state, units).length; const fluent = fluentPhrases(state, units).length;
  const next = units.find(u => u.level === state.settings.level && !state.completedUnits.includes(u.id)) || units.find(u => !state.completedUnits.includes(u.id)) || units[0];
  const isResume = state.session && !state.session.stoppedAt;
  const date = new Date().toLocaleDateString('en', { weekday: 'long', month: 'long', day: 'numeric' });
  return <><div className="today-top"><span className="eyebrow">YOUR EVERYDAY SPANISH</span><span>{date}</span></div>
    <div className="welcome"><h1>A little practice.<br /><span>A world of conversation.</span></h1><p>Build the words, confidence, and habits to make Spanish yours.</p></div>
    <div className="dashboard-grid"><section className="practice-feature"><div className="feature-copy"><span className="tag"><span className="status-dot" /> YOUR NEXT STEP</span><h2>{isResume ? 'Pick up where\nyou left off.' : 'Let’s get\ntalking.'}</h2><p>{isResume ? 'Your place is saved. Come back to the same prompt, with the same support.' : 'A little new. A little review.\nA whole lot more you can say.'}</p><button className="button light" onClick={() => start('mixed')}>{isResume ? 'Resume my practice' : 'Start my practice'}<ArrowRight size={20} /></button><div className="feature-foot"><Clock size={15} /> {state.settings.dailyMinutes}-minute goal <span>·</span> Keep going at your pace</div></div><div className="word-art" aria-hidden="true"><span className="hola-word">hola<span>!</span></span><div className="speech-small">¿Qué tal?</div><span className="orbit one" /><span className="orbit two" /><span className="tiny-spark">✳</span></div></section>
    <section className="daily-card"><div className="section-line"><h2>One day at a time</h2><Plant size={22} /></div><div className="daily-number">{data.todayAttempts}<span>practice attempts today</span></div><div className="week-strip">{Array.from({ length: 7 }, (_, i) => { const d = new Date(); d.setDate(d.getDate() - 6 + i); const key = d.toDateString(); const active = activity.some(a => new Date(a.at).toDateString() === key); return <div key={i} className={i === 6 ? 'today' : ''}><span>{d.toLocaleDateString('en', { weekday: 'short' }).slice(0, 1)}</span><span className={`day-circle ${active ? 'done' : ''}`}>{active ? <Check size={15} weight="bold" /> : d.getDate()}</span></div>; })}</div><div className="daily-bottom"><span><strong>{data.streak}</strong> {data.streak === 1 ? 'day' : 'days'} of practice</span><a href="#progress">See progress <ArrowUpRight size={16} /></a></div><p className="micro">Small sessions count. Rest helps learning, too.</p></section></div>
    <section className="conversation-launch"><div><span className="eyebrow">GO BEYOND THE LESSON</span><h2>Where will the conversation go?</h2><p>Talk freely with your on-device AI partner, or rehearse a practical mission before trying it in the world.</p></div><div className="button-row"><a className="button" href="#coach">Talk with AI <ChatCircleDots size={19} /></a><a className="button secondary" href="#missions">Try a mission</a><a className="text-link" href="#calls">Translate a live call <ArrowUpRight size={17} /></a></div></section>
    {state.coachingNote && <div className="notice"><strong>Your imported next step</strong><p>{state.coachingNote}</p></div>}
    <div className="section-line section-heading"><h2>Find your flow</h2><span className="muted">A different way in, every day.</span></div>
    <div className="practice-options"><button onClick={() => start('review')} className="option"><div className="option-icon green"><CalendarBlank size={24} /></div><div><h3>Make it stick</h3><p>{due ? `${due} phrases ready to revisit` : 'Recall, review, remember'}</p></div><ArrowUpRight size={21} /></button><button onClick={() => start('listening')} className="option"><div className="option-icon sand"><Headphones size={24} /></div><div><h3>Tune your ear</h3><p>Listen. Notice. Understand.</p></div><ArrowUpRight size={21} /></button><button onClick={() => start('fluency')} className="option"><div className="option-icon leaf"><Timer size={24} /></div><div><h3>Say it smoothly</h3><p>{fluent ? `${fluent} familiar ${fluent === 1 ? 'phrase' : 'phrases'}` : 'After independent recall'}</p></div><ArrowUpRight size={21} /></button><button onClick={() => startDialogue(state.roleplay && !state.roleplay.completedAt ? state.roleplay.unitId : next.id)} className="option"><div className="option-icon pink"><ChatCircleDots size={24} /></div><div><h3>{state.roleplay && !state.roleplay.completedAt ? 'Resume your conversation' : 'Use it in real life'}</h3><p>Take your turn in a conversation</p></div><ArrowUpRight size={21} /></button></div>
    <div className="course-preview"><div><div className="section-line"><h2>Your learning path</h2><a className="text-link" href="#course">Explore the course <ArrowRight size={17} /></a></div><div className="path-preview"><div className="path-marker"><BookOpen size={28} /></div><div className="path-copy"><span className="eyebrow">{next.level} · {next.level === 'A1' ? 'THE FOUNDATIONS' : next.level === 'A2' ? 'FIND YOUR INDEPENDENCE' : 'BUILD YOUR VOICE'}</span><h3>{next.title}</h3><p>{next.description}</p><div className="path-meta"><span>{next.phrases.filter(p => state.progress[p.id]).length} / {next.phrases.length} phrases practiced</span><Meter value={next.phrases.filter(p => state.progress[p.id]).length} max={next.phrases.length} label="Unit practice" /></div></div><a className="circle-button" aria-label={`Open ${next.title}`} href={`#course/${next.id}`}><ArrowRight size={21} /></a></div></div><aside className="method-note"><span className="eyebrow">THE HABLA WAY</span><h3>Try to remember.<br />Then make it real.</h3><p>Recall first. Get a little help when you need it. Come back after a break.</p><a className="text-link" href="#method">Why it works <ArrowUpRight size={16} /></a></aside></div>
  </>;
}
