import { ArrowUpRight } from '@phosphor-icons/react';
import { PageIntro } from './shared';
export function Method() {
  return <><PageIntro label="THE HABLA WAY" title="Practice with a purpose.">Built around useful learning principles. Honest about what an app can do.</PageIntro><div className="method-grid">{[
    ['01', 'Recall before reveal.', 'Trying to retrieve something strengthens later memory. Familiar phrases stay hidden until you try, while new material comes with meaning and a model. Repeating a visible answer is tracked as supported practice.', 'Retrieval practice research', 'https://pubmed.ncbi.nlm.nih.gov/16507066/'],
    ['02', 'Leave a little space.', 'Reviews return after a gap. Successful independent recall lengthens intervals; difficulty brings a phrase back sooner. The starting 1, 3, 7, 14 day schedule is adjustable, not a scientifically perfect formula.', 'Spacing in language learning', 'https://onlinelibrary.wiley.com/doi/abs/10.1111/lang.12479'],
    ['03', 'Understand. Say. Use.', 'Pair short explanations with listening, stories and changed-context prompts. After you can recall a phrase on your own, a fluency pass asks you to say it again. A suggested pace stays visible and never checks the answer for you. Each unit also has a real-world mission, because rehearsing an exchange and having a real conversation are different skills.', 'The four strands of language learning', 'https://www.wgtn.ac.nz/lals/resources/paul-nations-resources/paul-nations-publications/publications/documents/2007-Four-strands.pdf'],
    ['04', 'Make errors useful.', 'See a natural model, notice the useful correction, and try again. Then revisit the idea later. Text matching accepts curated alternatives, but cannot recognize every valid response or assess pronunciation.', 'Corrective feedback research', 'https://www.cambridge.org/core/journals/studies-in-second-language-acquisition/article/oral-feedback-in-classroom-sla/4999EE1C8379B2BF026B148EAF373CA1'],
    ['05', 'Make room for rest.', 'Short goals are there to help you return. You can keep going, but exhausting repetition is not the aim. Breaks and sleep support learning; missed days never generate invented activity.', 'Sleep and memory review', 'https://pubmed.ncbi.nlm.nih.gov/23589831/'],
    ['06', 'Measure the right things.', 'Habla tracks observable practice, independent recall and use in a different prompt. A fluency pass counts as practice and leaves your review dates unchanged. Unit completion is not certification. No app can promise record-speed fluency or replace all real-world exposure.', 'Interaction and language learning', 'https://www.cambridge.org/core/journals/language-teaching/article/interaction-and-instructed-second-language-acquisition/78A156EE200F744F5978F99BFB073DBE']
  ].map(([n, title, text, label, url]) => <section className="method-block" key={n}><span>{n}</span><h2>{title}</h2><p>{text}</p><a href={url} target="_blank" rel="noreferrer">{label} <ArrowUpRight size={17} /></a></section>)}</div><section className="panel"><h2>What is included</h2><p>Guided A1 to B1 course material, repeatable practice, reading and listening passages, fluency passes over familiar phrases, 24 guided roleplay scenes, vocabulary review, custom phrases, progress history and backup. The authored course is finite. You can keep reviewing it and add your own phrases. A fluency pass does not measure speaking speed as a score or assess pronunciation.</p><p>Speech audio uses browser voices. Optional dictation may use your browser provider’s servers and always lets you edit before checking. The Mac companion adds on-device, open-ended AI conversation with spoken replies. It uses a compact rolling context, so earlier details may need a reminder. It does not assess pronunciation or certify proficiency.</p><h2>Mission practice, grounded in public CIA descriptions</h2><p>Prepare useful language, rehearse a situation, adapt it to a new context, and debrief a real-world attempt. Optional Spanish-first practice comes after preparation, with English help always available. Help and model answers remain visible in your practice record.</p><p>This is an independent adaptation of publicly described training practices. It is not an official CIA course or certification, and it makes no accelerated-fluency promise.</p><p><a href="https://www.cia.gov/stories/story/language-empowers-mission/" target="_blank" rel="noreferrer">CIA: Language empowers mission</a> · <a href="https://www.cia.gov/readingroom/docs/CIA-RDP86-00244R000200300011-0.pdf" target="_blank" rel="noreferrer">Historical language training highlights</a></p><h2>Your data stays yours</h2><p>Habla does not have accounts or a cloud learner database. Progress stays in your browser’s local storage. Other visitors cannot see it. Export a backup to move devices or protect against cleared browser data. Mac conversations are saved separately on that device and have their own transcript export. Call transcripts stay in your Mac’s Documents folder. ChatGPT integration is an explicit copy/paste import and export, not automatic synchronization.</p></section></>;
}
