import { ArrowUpRight } from '@phosphor-icons/react';
import { PageIntro } from './shared';
export function Method() {
  return <><PageIntro label="THE HABLA WAY" title="Practice with a purpose.">Built around useful learning principles. Honest about what an app can do.</PageIntro><div className="method-grid">{[
    ['01', 'Recall before reveal.', 'Trying to retrieve something strengthens later memory. Familiar phrases stay hidden until you try, while new material comes with meaning and a model. Repeating a visible answer is tracked as supported practice.', 'Retrieval practice research', 'https://pubmed.ncbi.nlm.nih.gov/16507066/'],
    ['02', 'Leave a little space.', 'Reviews return after a gap. Successful independent recall lengthens intervals; difficulty brings a phrase back sooner. The starting 1, 3, 7, 14 day schedule is adjustable, not a scientifically perfect formula.', 'Spacing in language learning', 'https://onlinelibrary.wiley.com/doi/abs/10.1111/lang.12479'],
    ['03', 'Understand. Say. Use.', 'Pair short explanations with listening, stories and changed-context prompts. Each unit has a real-world mission because rehearsing an exchange and having a real conversation are different skills.', 'The four strands of language learning', 'https://www.wgtn.ac.nz/lals/resources/paul-nations-resources/paul-nations-publications/publications/documents/2007-Four-strands.pdf'],
    ['04', 'Make errors useful.', 'See a natural model, notice the useful correction, and try again. Then revisit the idea later. Text matching accepts curated alternatives, but cannot recognize every valid response or assess pronunciation.', 'Corrective feedback research', 'https://www.cambridge.org/core/journals/studies-in-second-language-acquisition/article/oral-feedback-in-classroom-sla/4999EE1C8379B2BF026B148EAF373CA1'],
    ['05', 'Make room for rest.', 'Short goals are there to help you return. You can keep going, but exhausting repetition is not the aim. Breaks and sleep support learning; missed days never generate invented activity.', 'Sleep and memory review', 'https://pubmed.ncbi.nlm.nih.gov/23589831/'],
    ['06', 'Measure the right things.', 'Habla tracks observable practice, independent recall and use in a different prompt. Unit completion is not certification. No app can promise record-speed fluency or replace all real-world exposure.', 'Interaction and language learning', 'https://www.cambridge.org/core/journals/language-teaching/article/interaction-and-instructed-second-language-acquisition/78A156EE200F744F5978F99BFB073DBE']
  ].map(([n, title, text, label, url]) => <section className="method-block" key={n}><span>{n}</span><h2>{title}</h2><p>{text}</p><a href={url} target="_blank" rel="noreferrer">{label} <ArrowUpRight size={17} /></a></section>)}</div><section className="panel"><h2>What is included</h2><p>Guided A1 to B1 course material, repeatable practice, reading and listening passages, 24 guided roleplay scenes, vocabulary review, custom phrases, progress history and backup. The authored course is finite. You can keep reviewing it and add your own phrases.</p><p>Speech audio uses browser voices. Optional dictation may use your browser provider’s servers and always lets you edit before checking. No pronunciation score or open-ended AI conversation is claimed.</p><h2>Your data stays yours</h2><p>Habla does not have accounts or a cloud learner database. Progress stays in your browser’s local storage. Other visitors cannot see it. Export a backup to move devices or protect against cleared browser data. ChatGPT integration is an explicit copy/paste import and export, not automatic synchronization.</p></section></>;
}
