import { useState } from 'react';
import { BookmarkSimple, Plus, MagnifyingGlass, X, ArrowRight } from '@phosphor-icons/react';
import type { AppState, Phrase, Unit } from '../types';
import { allPhrases } from '../lib/engine';
import { PageIntro, Listen, Empty, stageLabels } from './shared';
export function Phrasebook({ state, units, update }: { state: AppState; units: Unit[]; update: (s: AppState) => void }) {
  const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [adding, setAdding] = useState(false); const [spanish, setSpanish] = useState(''); const [english, setEnglish] = useState(''); const [notice, setNotice] = useState('');
  const phrases = allPhrases(units, state).filter(p => `${p.spanish} ${p.english}`.toLowerCase().includes(query.toLowerCase()) && (filter === 'all' || filter === 'saved' && state.bookmarks.includes(p.id) || filter === 'mine' && p.unitId === 'custom' || filter === 'practiced' && state.progress[p.id]));
  function add() { if (!spanish.trim() || !english.trim()) return; const id = `custom-${Date.now()}`; const p: Phrase = { id, unitId: 'custom', spanish: spanish.trim(), english: english.trim(), alternatives: [], explanation: 'Your own phrase. Compare with a trusted source when you need language guidance.', hint: `It starts with “${spanish.trim().split(' ')[0]}”.`, example: spanish.trim(), exampleEnglish: english.trim(), context: `Say in Spanish: ${english.trim()}`, contextAnswers: [spanish.trim()], tags: ['custom'] }; update({ ...state, customPhrases: [...state.customPhrases, p] }); setSpanish(''); setEnglish(''); setAdding(false); setFilter('mine'); setNotice('Phrase added. It will appear in your mixed practice.'); }
  return <><PageIntro label="WORDS TO KEEP" title="Your Spanish, collected." action={<button className="button" onClick={() => setAdding(!adding)}><Plus size={18} /> Add a phrase</button>}>A useful phrase today. A natural response tomorrow.</PageIntro>{notice && <p className="notice" role="status">{notice}</p>}{adding && <form className="panel add-phrase" onSubmit={e => { e.preventDefault(); add(); }}><div className="section-line"><h2>Make room for a new phrase</h2><button type="button" className="icon-button" aria-label="Close add phrase" onClick={() => setAdding(false)}><X size={20} /></button></div><div className="form-columns"><label>Spanish<input required maxLength={300} value={spanish} onChange={e => setSpanish(e.target.value)} placeholder="¿Me puedes ayudar?" /></label><label>English meaning<input required maxLength={300} value={english} onChange={e => setEnglish(e.target.value)} placeholder="Can you help me?" /></label></div><button className="button" type="submit">Save phrase <ArrowRight size={18} /></button></form>}<div className="library-tools"><div className="search"><MagnifyingGlass size={20} /><input aria-label="Search phrases" placeholder="Find a word or phrase…" value={query} onChange={e => setQuery(e.target.value)} /></div><div className="filter-tabs">{[['all', 'All phrases'], ['practiced', 'Practiced'], ['saved', 'Saved'], ['mine', 'My phrases']].map(([id, label]) => <button key={id} aria-pressed={filter === id} className={filter === id ? 'active' : ''} onClick={() => setFilter(id)}>{label}</button>)}</div></div><p className="micro">{phrases.length} phrases · Tap the bookmark to keep something close.</p><div className="phrase-grid">{phrases.map(p => <article className="phrase-card" key={p.id}><div className="section-line"><span className="phrase-unit">{units.find(u => u.id === p.unitId)?.title || 'Your phrase'}</span><button className="icon-button" aria-label={`${state.bookmarks.includes(p.id) ? 'Unsave' : 'Save'} ${p.spanish}`} aria-pressed={state.bookmarks.includes(p.id)} onClick={() => update({ ...state, bookmarks: state.bookmarks.includes(p.id) ? state.bookmarks.filter(id => id !== p.id) : [...state.bookmarks, p.id] })}><BookmarkSimple size={21} weight={state.bookmarks.includes(p.id) ? 'fill' : 'regular'} /></button></div><h2 lang="es">{p.spanish}</h2><p>{p.english}</p><div className="section-line"><Listen text={p.spanish} settings={state.settings} /><span className="stage-label">{state.progress[p.id] ? stageLabels[state.progress[p.id].stage] : 'Not practiced yet'}</span></div></article>)}</div>{!phrases.length && <Empty title="A little space for your Spanish.">{filter === 'mine' ? 'Add a phrase you want to use, and make it part of your practice.' : 'Try a different search or save a phrase to find it here.'}</Empty>}</>;
}
