import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowLeft, Lightbulb, Eye, Check, Microphone, Stop, Headphones, ChatCircleDots, CheckCircle, Clock } from '@phosphor-icons/react';
import type { AppState, Unit } from '../types';
import { allPhrases, submitAnswer, nextExercise, giveHint, revealAnswer, stopSession, duePhrases } from '../lib/engine';
import { cancelSpeech, getRecognition, type RecognitionInstance } from '../lib/audio';
import { Empty, Listen } from './shared';
export function Practice({ state, units, update, go, saved }: { state: AppState; units: Unit[]; update: (s: AppState) => void; go: (route: string) => void; saved: boolean }) {
  const session = state.session; const ex = session?.exercise;
  const phrase = allPhrases(units, state).find(p => p.id === ex?.phraseId);
  const practicePhrases = allPhrases(units, state);
  const lastDifficult = [...state.attempts].reverse().find(attempt => !attempt.correct && session?.practicedIds.includes(attempt.phraseId));
  const nextFocus = practicePhrases.find(item => item.id === lastDifficult?.phraseId) || duePhrases(state, units)[0] || phrase;
  const readyForContext = nextFocus && ['independent', 'transfer'].includes(state.progress[nextFocus.id]?.stage);
  const [listening, setListening] = useState(false); const [speechNotice, setSpeechNotice] = useState(''); const [micInfo, setMicInfo] = useState(false);
  const [elapsed, setElapsed] = useState(0);
  const recognition = useRef<RecognitionInstance | null>(null); const answerRef = useRef<HTMLTextAreaElement>(null);
  const currentState = useRef(state); currentState.current = state;
  function setAnswer(response: string) { const s = currentState.current; if (s.session?.exercise && !s.session.exercise.answered) update({ ...s, session: { ...s.session, exercise: { ...s.session.exercise, response: response.slice(0, 2000) } } }); }
  const finishListening = () => { recognition.current?.stop(); setListening(false); };
  useEffect(() => () => { recognition.current?.abort(); cancelSpeech(); }, []);
  useEffect(() => { const tick = () => setElapsed(session ? Math.max(0, Math.floor((Date.now() - Date.parse(session.startedAt)) / 60000)) : 0); tick(); const timer = setInterval(tick, 15000); return () => clearInterval(timer); }, [session?.startedAt]);
  useEffect(() => { if (ex && !ex.answered) answerRef.current?.focus(); }, [ex?.phraseId, ex?.kind, ex?.retry]);
  function beginDictation() {
    const Recognition = getRecognition(); if (!Recognition) { setSpeechNotice('Dictation is unavailable in this browser. Type your answer, or use your device keyboard’s microphone.'); return; }
    cancelSpeech(); recognition.current?.abort(); const rec = new Recognition(); recognition.current = rec;
    rec.lang = ex?.kind === 'comprehension' ? 'en-US' : 'es-MX'; rec.continuous = true; rec.interimResults = true;
    const initial = currentState.current.session?.exercise?.response || '';
    rec.onresult = event => { const transcript = Array.from(event.results as ArrayLike<any>).map((r: any) => r[0].transcript).join(' '); setAnswer(`${initial} ${transcript}`.trim()); };
    rec.onerror = event => { setListening(false); setSpeechNotice(event.error === 'not-allowed' ? 'Microphone permission was not granted. You can type your answer instead.' : 'Dictation stopped. Check the text before submitting, or keep typing.'); };
    rec.onend = () => { setListening(false); };
    try { rec.start(); setListening(true); setSpeechNotice('Take your time. Your answer is only checked when you choose Check answer.'); } catch { setSpeechNotice('Could not start dictation. You can type your answer instead.'); }
  }
  function end() { finishListening(); cancelSpeech(); update(stopSession(currentState.current)); }
  function check() { finishListening(); const text = currentState.current.session?.exercise?.response || ''; if (/^(stop|stop practice|end session|parar|terminar)$/i.test(text.trim().replace(/[.!?¡¿]+$/g, '').trim())) { end(); return; } update(submitAnswer(currentState.current, units, text)); }
  if (!session) return <Empty title="Your next conversation starts here." action={<button className="button" onClick={() => go('today')}>Go to today <ArrowRight /></button>}>Start a session from your dashboard or choose a unit in the course.</Empty>;
  if (session.stoppedAt) return <div className="session-summary"><div className="summary-icon"><CheckCircle size={42} /></div><span className="eyebrow">UNTIL NEXT TIME</span><h1>{saved ? 'Practice saved.' : 'Practice complete.'}</h1>{!saved && <p role="alert">Your progress is only in this tab. Download a backup in Preferences before closing it.</p>}<p>A little more Spanish to take into your day.</p><div className="summary-stats"><div><strong>{session.count}</strong><span>attempts</span></div><div><strong>{session.correct}</strong><span>correct responses</span></div><div><strong>{session.supported}</strong><span>with support</span></div></div><section className="panel"><h2>What you practiced</h2>{session.practicedIds.length ? [...new Set(session.practicedIds)].slice(-8).map(id => { const p = allPhrases(units, state).find(x => x.id === id); return p ? <div className="recap-line" key={id}><span lang="es">{p.spanish}</span><span>{state.progress[id]?.stage === 'independent' || state.progress[id]?.stage === 'transfer' ? 'Recall recorded' : 'Keep revisiting'}</span></div> : null; }) : <p>No attempts recorded yet. Your next prompt is waiting.</p>}<div className="next-focus"><span className="eyebrow">YOUR NEXT PROMPT</span><p>{nextFocus ? (readyForContext && nextFocus.context ? nextFocus.context : `Say in Spanish: “${nextFocus.english}”`) : 'Choose the next unit in your course to learn a new phrase.'}</p><span className="micro">{readyForContext ? 'You have recalled this independently. Next, change a detail or use it in a dialogue.' : 'Try after a break with the model hidden. Revisit difficult wording before adding more detail.'}</span></div></section><button className="button" onClick={() => go('today')}>Back to today <ArrowRight size={18} /></button></div>;
  if (!ex || !phrase) return <Empty title="You’re up to date." action={<button className="button" onClick={end}>Save session</button>}>No items are ready for this session. Choose another unit or add your own phrases.</Empty>;
  const showModel = ex.introduced || ex.support === 'revealed' || ex.answered || ex.retry;
  const isContext = ex.kind === 'context'; const isListening = ex.kind === 'listening'; const isMeaning = ex.kind === 'comprehension';
  const answer = isContext ? phrase.contextAnswers[0] : isMeaning ? phrase.english : phrase.spanish;
  const unit = units.find(u => u.id === phrase.unitId);
  return <div className="practice-page"><div className="practice-top"><a href="#today" className="back-link"><ArrowLeft size={18} /> Pause & save</a><span className="practice-count">{session.count} attempts <span>·</span> {elapsed} / {state.settings.dailyMinutes} min</span><button className="text-button" onClick={end}>End session</button></div><div className="practice-track"><span style={{ width: `${Math.min(100, session.count / 12 * 100)}%` }} /></div><div className="practice-heading"><span className="eyebrow">{unit?.title || 'YOUR PHRASES'}</span><span className={`tag ${ex.introduced ? 'sand' : 'green'}`}>{ex.introduced ? 'Learn something new' : ex.retry ? 'One supported retry' : isContext ? 'A new context' : isListening ? 'Listen & write' : isMeaning ? 'Understand it' : 'Recall it'}</span></div>
    <section className="exercise-card"><div className="exercise-symbol">{isListening ? <Headphones size={28} /> : isContext ? <ChatCircleDots size={28} /> : <span>habla.</span>}</div><p className="exercise-instruction">{ex.introduced ? 'Take in the meaning. Then try it yourself.' : ex.retry ? 'Use the correction for one more attempt.' : isContext ? 'Say it in Spanish.' : isListening ? 'Listen, then write what you hear in Spanish.' : isMeaning ? 'What does this mean in English?' : 'How would you say this in Spanish?'}</p>
    <h1 className="exercise-prompt" lang={isMeaning ? 'es' : 'en'}>{isContext ? phrase.context : isListening && !showModel ? 'Listen closely.' : isMeaning ? phrase.spanish : phrase.english}</h1>
    {isListening && <Listen text={phrase.spanish} settings={state.settings} label="Play Spanish audio" />}
    {showModel && <div className="model-answer"><span className="eyebrow">{ex.introduced ? 'YOUR NEW PHRASE' : 'A NATURAL ANSWER'}</span><p lang={isMeaning ? 'en' : 'es'}>{answer}</p>{!isMeaning && <Listen text={answer} settings={state.settings} label="Hear the answer" />}<div className="explanation">{phrase.explanation}</div>{ex.introduced && <div className="example"><strong lang="es">{phrase.example}</strong><span>{phrase.exampleEnglish}</span></div>}</div>}
    {ex.support === 'hint' && !showModel && <div className="hint-box" role="status"><Lightbulb size={19} /> {isContext ? 'Use the sentence pattern you practiced. Change the detail requested by the prompt.' : phrase.hint}</div>}
    <form onSubmit={e => { e.preventDefault(); check(); }}><label htmlFor="practice-answer">Your answer</label><div className={`answer-area ${ex.answered ? ex.correct ? 'answer-correct' : 'answer-review' : ''}`}><textarea ref={answerRef} id="practice-answer" rows={3} maxLength={2000} autoComplete="off" autoCorrect="off" spellCheck={false} value={ex.response} disabled={ex.answered} onChange={e => setAnswer(e.target.value)} placeholder={isMeaning ? 'Write the meaning in English…' : 'Write in Spanish, or use the microphone…'} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); if (!ex.answered && ex.response.trim() && !listening) check(); } }} />{!ex.answered && <button className={`mic-button ${listening ? 'recording' : ''}`} type="button" aria-label={listening ? 'Finish speaking' : 'Use microphone'} onClick={() => listening ? finishListening() : setMicInfo(true)}>{listening ? <Stop size={22} weight="fill" /> : <Microphone size={22} />}</button>}</div>
    {micInfo && <div className="mic-disclosure"><p>Optional browser dictation may send audio to your browser provider. Habla does not store recordings. It transcribes words, not pronunciation quality.</p><button className="button small" type="button" onClick={() => { setMicInfo(false); beginDictation(); }}>Enable dictation</button><button className="text-button" type="button" onClick={() => setMicInfo(false)}>Keep typing</button></div>}
    {speechNotice && <p className="micro" role="status">{speechNotice}</p>}
    {ex.answered ? <div className={`feedback ${ex.correct ? 'correct' : 'review'}`} data-testid="feedback" role="status"><div><strong>{ex.correct ? <><Check size={20} /> Correct{ex.support !== 'none' ? ', with support.' : '.'}</> : 'Let’s adjust that.'}</strong><p>{ex.feedback}</p></div><button className="button" type="button" onClick={() => { cancelSpeech(); setSpeechNotice(''); update(nextExercise(currentState.current, units)); }}>Continue <ArrowRight size={18} /></button></div> : <div className="exercise-actions"><div><button type="button" className="text-button" onClick={() => update(giveHint(currentState.current))} disabled={showModel}><Lightbulb size={19} /> Small hint</button><button type="button" className="text-button" onClick={() => update(revealAnswer(currentState.current))} disabled={showModel}><Eye size={19} /> Reveal</button></div><button type="submit" className="button" disabled={!ex.response.trim() || listening}>Check answer <ArrowRight size={18} /></button></div>}
    </form></section><div className="practice-reassurance"><span><CheckCircle size={16} /> {saved ? 'Progress saved on this device' : 'Progress is only in this tab'}</span><span>Thinking time is learning time.</span></div>{elapsed >= state.settings.dailyMinutes && <div className="goal-notice"><Clock size={20} /><div><strong>You’ve reached your session goal.</strong><p>Take a break when you need one. You can keep practicing or end and save anytime.</p></div></div>}<p className="micro center">Missing accents are okay here. If dictation changes your words, edit them before checking. Type “stop” to save and finish.</p></div>;
}
